Repository luigimonteforte5/EventOrganizer, pull requests merged in 2025-04, with the labels that each got.

#2 Readme
  readme.md
Labels: documentation

#1 Add docker compose and database configuration
  .gitignore
  docker-compose-db.yaml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Configuration

#3 Update dependencies
  pom.xml
Labels: Configuration

#5 User Flow
  src/main/java/org/example/eventorganizer/EventOrganizerApplication.java
  src/main/java/org/example/eventorganizer/mapper/GenericMapper.java
  src/main/java/org/example/eventorganizer/mapper/impl/UserMapper.java
  src/main/java/org/example/eventorganizer/security/config/SecurityConfig.java
  src/main/java/org/example/eventorganizer/user/controller/UserController.java
  src/main/java/org/example/eventorganizer/user/enums/UserRole.java
  src/main/java/org/example/eventorganizer/user/model/User.java
  src/main/java/org/example/eventorganizer/user/model/UserDTO.java
  src/main/java/org/example/eventorganizer/user/repository/UserRepository.java
  src/main/java/org/example/eventorganizer/user/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#6 Added event test creation flow
  src/main/java/org/example/eventorganizer/event/controller/EventController.java
  src/main/java/org/example/eventorganizer/event/enums/EventStatus.java
  src/main/java/org/example/eventorganizer/event/enums/EventType.java
  src/main/java/org/example/eventorganizer/event/model/Event.java
  src/main/java/org/example/eventorganizer/event/model/EventDTO.java
  src/main/java/org/example/eventorganizer/event/repository/EventRepository.java
  src/main/java/org/example/eventorganizer/event/service/EventService.java
  src/main/java/org/example/eventorganizer/mapper/impl/EventMapper.java
Labels: enhancement

#8 Adds relations to user and event entities
  src/main/java/org/example/eventorganizer/event/model/Event.java
  src/main/java/org/example/eventorganizer/event/model/EventDTO.java
  src/main/java/org/example/eventorganizer/user/model/User.java
  src/main/java/org/example/eventorganizer/user/model/UserDTO.java
Labels: enhancement

#9 Add database updating for registered users
  src/main/java/org/example/eventorganizer/security/config/SecurityConfig.java
  src/main/java/org/example/eventorganizer/user/enums/UserRole.java
  src/main/java/org/example/eventorganizer/user/model/User.java
  src/main/java/org/example/eventorganizer/user/model/UserDTO.java
  src/main/java/org/example/eventorganizer/user/repository/UserRepository.java
  src/main/java/org/example/eventorganizer/user/service/UserService.java
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/db/changelog/init.sql
  src/main/resources/db/changelog/versions/17-01-changelog.sql
  src/main/resources/db/changelog/versions/17-01-changelog2.sql
Labels: enhancement
